harfbuzz: Autospec creation for update from version 8.3.1 to version 8.4.0
Behdad Esfahbod (4):
      [buffer] Add API for random state
      [shape] Fix syntax error under some configs
      [wasm] Update to latest wasm-micro-runtime API
      Update README.md

Garret Rieger (10):
      [subset] Update subset test suite to match some changes made to fonttools.
      [subset] Update generate-expected-outputs to drop BASE.
      [subset] Match hb rounding to fonttools for avg char width.
      [subset] Move post apply mvar test intance position to avoid rounding diff.
      [subset] Disable fonttools comparison in a few tests where rounding diffs show up.
      [subset] place the gdef var store at the end of the GDEF table.
      [subset] add virtual links to keep the gdef varstore last.
      [subset] cast.
      [subset] updated comment.
      [repacker] add tests of serializer repack_last().

Khaled Hosny (3):
      [autotools] Check for minimum ICU version as well
      [meson] Check minimum dependency versions like with autotools
      8.4.0

Ozkan Sezer (3):
      hb-common.h: restore including stdint.h for VS2010/2012.
      tests, hb-test.h: define g_assert_false && g_assert_nonnull for old glib
      configure.ac: bump minimum required versions for glib and cairo.

dependabot[bot] (6):
      Bump fonttools from 4.49.0 to 4.50.0 in /.ci
      Bump setuptools from 69.1.1 to 69.2.0 in /.ci
      Bump meson from 1.3.2 to 1.4.0 in /.ci
      Bump actions/checkout from 4.1.1 to 4.1.2
      Bump github/codeql-action from 3.24.6 to 3.24.7
      Bump github/codeql-action from 3.24.7 to 3.24.9

璀境石 (1):
      fixed: hb-subset.cc -- compile error C1128: number of sections exceeded object file format limit

Overview of changes leading to 8.4.0
Saturday, March 29, 2024
====================================
- Add /bigobj to MSVC compiler flags in meson build, to fix building hb-subset.cc
- Specify minimum versions of various dependencies in meson and autotools build.
- When subsetting, place variation store at the end of “GDEF” table  to fix
  shaping issues with some versions of Adobe InDesign.
- Various build fixes.

- New API:
+hb_buffer_set_random_state()
+hb_buffer_get_random_state()